config/routes.rb
Rails.application.routes.draw do

  root :to => 'static_pages#home'

  get '/home',    to: 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { |user| user.email = user.email.downcase }

  validates :name, presence: true, length: { maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[\w+\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sentitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis
def full_title(page_title)
    base_title = 'Ruby on Rails Tutorial Sample App'
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><a href="http://news.railsturorial.org">News</a></li>
      </ul>
    </nav>
  </small>

app/views/layouts/_header.html.erb
<div class="navbar-inner">
  <div class="container">
    <%= link_to "sample app", root_path , id: "logo" %>
    <nav>
      <ul class = "pull-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Sign in", '#' %></li>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9] -->
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<!--endif-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <header class = "navbar navbar-fixed-top">
      <%= render 'layouts/header' %>
    </header>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<%= provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  This is the home page for the Nori's project.
</p>

app/views/static_pages/contact.html.erb
<%= provide(:title, 'Contact')%>
<h1>Contact</h1>
<p>
  This is the contact page for the Nori's project.
</p>

app/views/static_pages/help.html.erb
<%= provide(:title, 'Help') %>
    <h1>Help page</h1>
    <p>
      This is the home page for the Nori's project.
    </p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>
  <p>
    This is the home page for the Nori's project.
  </p>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-defaul" %>
</div>


<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>